Name:           ninja-build
Version:        1.6.0
Release:        3 
Summary:        A small build system with a focus on speed

License:        ASL 2.0
URL:            http://martine.github.com/ninja/
Source0:        https://github.com/martine/ninja/archive/ninja-%{version}.tar.gz
Source1:        ninja.vim

%description
Ninja is a small build system with a focus on speed. It differs from other
build systems in two major respects: it is designed to have its input files
generated by a higher-level build system, and it is designed to run builds as
fast as possible.


%prep
%setup -q -n ninja-%{version}


%build
CFLAGS="%{optflags}"
export CFLAGS
./configure.py --bootstrap

%install
# TODO: Install ninja_syntax.py?
install -p -m 755 -d %{buildroot}%{_bindir}
install -p -m 755 ninja %{buildroot}%{_bindir}/ninja

pushd %{buildroot}%{_bindir}
ln -sf ./ninja ninja-build
popd

#install -p -m 755 -d %{buildroot}%{_docdir}/%{name}-%{version}
#install -p -m 644 doc/manual.html %{buildroot}%{_docdir}/%{name}-%{version}/manual.html

install -p -m 755 -d %{buildroot}%{_datadir}/bash-completion/completions/
install -p -m 644 misc/bash-completion %{buildroot}%{_datadir}/bash-completion/completions/ninja

install -p -m 755 -d %{buildroot}%{_datadir}/vim/vimfiles/syntax
install -p -m 644 misc/ninja.vim %{buildroot}%{_datadir}/vim/vimfiles/syntax/ninja.vim
install -p -m 755 -d %{buildroot}%{_datadir}/vim/vimfiles/ftdetect
install -p -m 644 %{SOURCE1} %{buildroot}%{_datadir}/vim/vimfiles/ftdetect/ninja.vim


%files
%doc COPYING README
%{_bindir}/ninja
%{_bindir}/ninja-build
# bash-completion does not own this
%{_datadir}/bash-completion/completions/ninja
%{_datadir}/vim/vimfiles/syntax/ninja.vim
%{_datadir}/vim/vimfiles/ftdetect/ninja.vim


%changelog
* Fri Oct 23 2015 cjacker - 1.6.0-3
- Rebuild for new 4.0 release

* Thu Jul 30 2014 Cjacker <cjacker@foxmail.com>
- update to 1.6.0
* Tue Dec 10 2013 Cjacker <cjacker@gmail.com>
- first build, prepare for the new release.

