Name: cppunit
Version: 1.12.1
Release: 10%{?dist}

Summary: C++ unit testing framework
# no license in files
License: LGPLv2+
Url: http://cppunit.sourceforge.net/
Source: http://downloads.sourceforge.net/cppunit/cppunit-%{version}.tar.gz
Patch0: cppunit-1.12.0-nolibdir.patch
Patch1: cppunit-msg.patch
#https://sourceforge.net/tracker/?func=detail&aid=2912630&group_id=11795&atid=311795
Patch2: cppunit-warnings-sf2912630.patch

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires: doxygen

%description
CppUnit is the C++ port of the famous JUnit framework for unit testing.
Test output is in XML for automatic testing and GUI based for supervised 
tests.

%package devel
Summary: Libraries and headers for cppunit development
Requires: pkgconfig, automake
Requires: %{name} = %{version}-%{release}

%description devel
This package contains the libraries and headers necessary for developing
programs that use cppunit.

%package doc
Summary: HTML formatted API documention for cppunit

%description doc
The cppunit-doc package contains HTML formatted API documention generated by
the popular doxygen documentation generation tool.

%prep
%setup -q
%patch0 -p1 -b .nolibdir
for file in THANKS ChangeLog NEWS; do
   iconv -f latin1 -t utf8 < $file > ${file}.utf8
   touch -c -r $file ${file}.utf8
   mv ${file}.utf8 $file
done
%patch1 -p1 -b .nomsg
%patch2 -p1 -b .warnings-sf2912630

%build
export LDFLAGS=-ldl
%configure --enable-doxygen --disable-static 
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT
make install DESTDIR=$RPM_BUILD_ROOT INSTALL='install -p'
rm $RPM_BUILD_ROOT%{_libdir}/*.la
# remove double of doc
rm -rf $RPM_BUILD_ROOT%{_datadir}/doc/cppunit

# ensure that timestamp of cppunit-config is the same for all arches
touch -c -r cppunit-config.in.nolibdir $RPM_BUILD_ROOT%{_bindir}/cppunit-config

# clean up examples
rm -rf __dist-examples __dist-examples-dir
cp -a examples __dist-examples
make -C __dist-examples distclean
# Makefile.am files are left as documentation
find __dist-examples \( -name Makefile.in -o -name .cvsignore -o -name '*.dsw' -o -name '*.dsp' \) -exec rm {} \;
chmod a-x __dist-examples/qt/run.bat
mkdir __dist-examples-dir
mv __dist-examples __dist-examples-dir/examples

%clean
rm -rf $RPM_BUILD_ROOT

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%doc AUTHORS COPYING NEWS README THANKS ChangeLog TODO BUGS doc/FAQ
%{_bindir}/DllPlugInTester
%{_libdir}/libcppunit*.so.*

%files devel
%defattr(-,root,root,-)
%{_bindir}/cppunit-config
%{_includedir}/cppunit
%{_libdir}/libcppunit.so
%{_datadir}/aclocal/cppunit.m4
%{_mandir}/man1/cppunit-config.1*
%{_libdir}/pkgconfig/cppunit.pc

%files doc
%defattr(-,root,root,-)
%doc __dist-examples-dir/examples/
%doc doc/html

%changelog
* Fri Oct 23 2015 cjacker - 1.12.1-10
- Rebuild for new 4.0 release

